### ISSUE TITLE
There's no index.js...

### ISSUE THREAD

**Issue by lachlansleight** [NimperX/react-aws-s3-typescript#1]
Hey! I'm not sure if I'm just being dumb, but it seems that the main entry point listed in package.json (dist/index.js) isn't being generated by your build. So I'm getting "unable to resolve path to module react-aws-s3-typescript" errors.

**Comment by NimperX** [comment]
Hello @lachlansleight,

Thank you for the submitting this issue. With the patch version `1.0.2` this issue has been resolved in the package. Feel free to submit a new issue with `enhancement` tag, if you have any feature request.
