### ISSUE TITLE
Handling CORS when trialling with localhost

### ISSUE THREAD

**Issue by jrd656** [NimperX/react-aws-s3-typescript#2]
Hi, I'm trying to set up a test upload call on a localhost. I'm getting a CORS error. Is there a way to navigate around this?

**Comment by NimperX** [comment]
Hi @jrd656,

When you are using S3 bucket you have to configure the CORS in your S3 bucket. Please follow [this guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/cors.html) to configure CORS. If you are still facing the issue, feel free to reply on this thread.

**Comment by NimperX** [comment]
@jrd656 I hope your issue has been fixed. Therefore I am closing this thread. If you arr still facing the issue, feel free to comment and reopen the issue at any time.

**Comment by ithustle** [comment]
Hi @NimperX. I'm facing this issue after following the guide you referenced above to configure CORS. Any tips? Did you able to upload to S3 on localhost?
