### ISSUE TITLE
Getting Buffer is not defined error when using it with webpack > 5

### ISSUE THREAD

**Issue by vaibhav-systango** [NimperX/react-aws-s3-typescript#4]
Hi,
Here's a screenshot of the error:
![image](https://user-images.githubusercontent.com/25978575/151966785-b0fe749e-112e-466d-b731-efaa509d2db3.png)

Here's my node version:
16.13.1

react-aws-s3-typescript: 1.1.3
webpack: 5.65.0
react: 17.0.2
react-dom: 17.0.2

**Comment by vaibhav-systango** [comment]
@NimperX

**Comment by arifshariati** [comment]
install buffer npm package `npm i buffer`

then use below at the top of your file.

`window.Buffer = window.Buffer || require('buffer').Buffer`

Hope this solves your problem.

**Comment by NimperX** [comment]
Hi @vaibhav-systango,

This issue is fixed in [v1.1.4](https://github.com/NimperX/react-aws-s3-typescript/releases/tag/v1.1.4)
