### ISSUE TITLE
URL adds file type which is not user friendly

### ISSUE THREAD

**Issue by MrFarhan** [NimperX/react-aws-s3-typescript#7]
## Steps to reproduce:
While uploading .docx file it includes `vnd.openxmlformats-officedocument.wordprocessingml (1).document` at the end of url which is not user-friendly.

## A sample file that I uploaded:
[file-sample_500kB.docx](https://github.com/NimperX/react-aws-s3-typescript/files/9766554/file-sample_500kB.docx)

## Issue:
URL includes a type that is not user friendly

## Expected result:
URL should only include standard user-friendly types (like .docx , .doc etc)

## Other information:
I also provide the file name to the upload call (i.e hello.docx).
#### Below is some data being sent in API call:

`key: file-sample_500kB.docx.vnd.openxmlformats-officedocument.wordprocessingml.document`
`acl: public-read`
`Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document`

**Comment by MrFarhan** [comment]
Is anyone looking into this issue?

**Comment by NimperX** [comment]
> Is anyone looking into this issue?

Yes @MrFarhan I am looking into this currently

**Comment by MrFarhan** [comment]
@NimperX It's really unprofessional to close the issue without any update on the issue.

**Comment by NimperX** [comment]
@MrFarhan So sorry for not putting an update on the issue. this issue is fixed in [v1.1.5](https://github.com/NimperX/react-aws-s3-typescript/releases/tag/v1.1.5). Please have a look and give feedback. Until your feedback is given, I'll keep this issue open.

**Comment by MrFarhan** [comment]
@NimperX Thank you for understanding, I am closing this issue as this is fixed in V1.1.5 as per your message, (I had delivered my project to the client with this exception).

I just wanted to know the status of this issue as i may use this library in future.
